name: tesla
description: "Control and monitor Tesla Products"
version: 0.2.1
homepage: "https://github.com/SpinlockLabs/tesla.dart"
authors:
- "Kenneth Endfinger <kaendfinger@gmail.com>"
environment:
  sdk: ">=2.0.0 <3.0.0"
